### ISSUE TITLE
A lil suggestion in the readme of the project

### ISSUE THREAD

**Issue by Jassi10000** [neutralinojs/gsoc2022#3]
@shalithasuranga Hey buddy 
While going through the points I found it written in a lil confusing way

![image](https://user-images.githubusercontent.com/64856348/158819474-c4969905-9591-4859-ae25-1541109cc369.png)

Can't the second point and third point be like this 
* Select a project idea out of the mentioned below
* If you have an idea of your own / want to initiate one , post its summary and goals in a new Github Discussion thread

Just a lil suggestion from my side , to make the sentences more understandable

**Comment by shalithasuranga** [comment]
Hey.. Thank you very much for the suggestion. Yeah indeed, now it looks clearer than the previous version. Feel free to send a pull request if you like :)

**Comment by shalithasuranga** [comment]
Thanks for sending a pull request :tada:. Hope we can close this one since it's merged?

**Comment by Jassi10000** [comment]
Sure sir , leme close this
